PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS tea_industry_catalog (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  enterprise_id TEXT NOT NULL REFERENCES enterprises(id),
  item_type TEXT NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  classification TEXT NOT NULL CHECK(classification IN ('open_media','mock')),
  geography_scope TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_url TEXT,
  local_path TEXT,
  license_name TEXT,
  license_url TEXT,
  author TEXT,
  mime_type TEXT,
  bytes INTEGER,
  sha256 TEXT,
  quality_score INTEGER NOT NULL CHECK(quality_score BETWEEN 0 AND 100),
  verification_status TEXT NOT NULL,
  truth_notice TEXT NOT NULL,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tea_catalog_type_class ON tea_industry_catalog(item_type, classification);
CREATE INDEX IF NOT EXISTS idx_tea_catalog_geography ON tea_industry_catalog(geography_scope);

DELETE FROM tea_industry_catalog WHERE organization_id = 'org-demo-guikesong';

INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('video-tea-picking-nuwara','org-demo-guikesong','ent-demo-matcha','video','Tea picking in Nuwara Eliya VID-20221103-WA0015.webm','鲜叶采摘','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ATea_picking_in_Nuwara_Eliya_VID-20221103-WA0015.webm','/demo/tea-media/video-tea-picking-nuwara.webm','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0','Muunaa-Selva','video/webm','9821587','5d39d361ad9c5a52625b0aa0d4faa598a11eb18f51309d95fe052ae940996fa2','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Tea picking in Nuwara Eliya VID-20221103-WA0015.webm","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/e/e2/Tea_picking_in_Nuwara_Eliya_VID-20221103-WA0015.webm?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2022-11-03","width":848,"height":480,"downloadedAt":"2026-08-29T18:09:26.653Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('video-driving-assam-estate','org-demo-guikesong','ent-demo-matcha','video','Driving through tea estate, Kinsukia, Assam, India.webm','茶园环境','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ADriving_through_tea_estate%2C_Kinsukia%2C_Assam%2C_India.webm','/demo/tea-media/video-driving-assam-estate.webm','CC BY-SA 3.0','https://creativecommons.org/licenses/by-sa/3.0','Subhashish Panigrahi','video/webm','10263832','ac30b8d7bdd689a221b206683ad2306bc98c60fd4eb4c2d9fb1ccce7b8b72903','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Driving through tea estate, Kinsukia, Assam, India.webm","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/a/a9/Driving_through_tea_estate%2C_Kinsukia%2C_Assam%2C_India.webm?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2013-07-18 13:25:03","width":1280,"height":720,"downloadedAt":"2026-08-29T18:09:27.033Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('video-dibrugarh-estates','org-demo-guikesong','ent-demo-matcha','video','Tea estates, Dibrugarh district, Assam.webm','茶园环境','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ATea_estates%2C_Dibrugarh_district%2C_Assam.webm','/demo/tea-media/video-dibrugarh-estates.webm','CC BY-SA 3.0','https://creativecommons.org/licenses/by-sa/3.0','Subhashish Panigrahi','video/webm','63042652','580252edc48884ab38669b5477eadf4cf8de3d91ace08b3980c6c37318bbcb78','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Tea estates, Dibrugarh district, Assam.webm","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/a/af/Tea_estates%2C_Dibrugarh_district%2C_Assam.webm?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2013-03-26 16:33:16","width":1280,"height":720,"downloadedAt":"2026-08-29T18:09:27.440Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('video-assam-garden','org-demo-guikesong','ent-demo-matcha','video','Tea garden Assam India.webm','茶园环境','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ATea_garden_Assam_India.webm','/demo/tea-media/video-assam-garden.webm','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0','Joy sagar Murmu','video/webm','52913245','b1e6a53ee2c0558025e7f111a5596d85299c1dd46b22667bf8db1408dc370949','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Tea garden Assam India.webm","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/a/a3/Tea_garden_Assam_India.webm?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2025-03-05","width":1920,"height":1080,"downloadedAt":"2026-08-29T18:09:27.849Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('video-jalpaiguri-garden','org-demo-guikesong','ent-demo-matcha','video','Tea Garden view near Jalpaiguri, North West Bengal.webm','茶园环境','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ATea_Garden_view_near_Jalpaiguri%2C_North_West_Bengal.webm','/demo/tea-media/video-jalpaiguri-garden.webm','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0','Rajani Gairshail','video/webm','18391742','df04ee150eaaef3b3b632f70ccedb63f5993431fb2941ffbd861b88a10d1be1a','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Tea Garden view near Jalpaiguri, North West Bengal.webm","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/f/f6/Tea_Garden_view_near_Jalpaiguri%2C_North_West_Bengal.webm?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2026-05-14","width":1080,"height":1920,"downloadedAt":"2026-08-29T18:09:28.205Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('video-tea-leaf-process','org-demo-guikesong','ent-demo-matcha','video','Coffee Bean & Tea Leaf Process.webm','加工流程','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ACoffee_Bean_%26_Tea_Leaf_Process.webm','/demo/tea-media/video-tea-leaf-process.webm','CC BY-SA 3.0','https://creativecommons.org/licenses/by-sa/3.0','Kelliks','video/webm','7032288','8639b40667ea34819a036a8be93d9b5682395344ab0803a92bf26fc1882b63cf','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Coffee Bean & Tea Leaf Process.webm","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/3/34/Coffee_Bean_%26_Tea_Leaf_Process.webm?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2013-04-11 14:42:03","width":960,"height":540,"downloadedAt":"2026-08-29T18:09:28.588Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('video-matcha-latte','org-demo-guikesong','ent-demo-matcha','video','Matcha latte whisking.webm','消费应用','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3AMatcha_latte_whisking.webm','/demo/tea-media/video-matcha-latte.webm','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0','Based5290','video/webm','65584442','e207a3bd407aa77923ed2c362446309b3dbe98fb30fc5ed2b2a4b4c9cdf6a081','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Matcha latte whisking.webm","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/b/b2/Matcha_latte_whisking.webm?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2026-01-30","width":1920,"height":1080,"downloadedAt":"2026-08-29T18:09:29.024Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('video-moroccan-tea','org-demo-guikesong','ent-demo-matcha','video','How Nomads prepare Moroccan tea.webm','消费文化','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3AHow_Nomads_prepare_Moroccan_tea.webm','/demo/tea-media/video-moroccan-tea.webm','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0','مصطفى ملو','video/webm','15545229','d029b1f55a3652e08b25e7984e8f4ad95063dcdefc2380bc0367f28d7053edfb','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:How Nomads prepare Moroccan tea.webm","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/5/59/How_Nomads_prepare_Moroccan_tea.webm?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2025-03-13","width":1920,"height":1080,"downloadedAt":"2026-08-29T18:09:29.434Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('video-oodaleah-estate','org-demo-guikesong','ent-demo-matcha','video','Oodaleah Tea Estate.webm','茶园环境','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3AOodaleah_Tea_Estate.webm','/demo/tea-media/video-oodaleah-estate.webm','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0','Owais Al Qarni','video/webm','31294973','cd6400527d8cecbdf4109d4abb105212608ac8508005b31ed9bbe2e3f72d162d','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Oodaleah Tea Estate.webm","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/7/75/Oodaleah_Tea_Estate.webm?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2024-12-13","width":1920,"height":1080,"downloadedAt":"2026-08-29T18:09:29.872Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('video-uganda-plantation','org-demo-guikesong','ent-demo-matcha','video','A closeup on the tea plantation in Western Uganda.webm','茶树近景','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3AA_closeup_on_the_tea_plantation_in_Western_Uganda.webm','/demo/tea-media/video-uganda-plantation.webm','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0','B722N','video/webm','79913085','a801bb47f8dc600225df8dbd0b9cd6b159122e9bef653c6300c732e467c7604f','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:A closeup on the tea plantation in Western Uganda.webm","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/5/55/A_closeup_on_the_tea_plantation_in_Western_Uganda.webm?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2025-07-10 16:28","width":1920,"height":1080,"downloadedAt":"2026-08-29T18:09:30.361Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('image-duyun-tea-farm-01','org-demo-guikesong','ent-demo-matcha','image','都匀牛场茶场 - panoramio.jpg','贵州茶园','open_media','贵州都匀实拍','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3A%E9%83%BD%E5%8C%80%E7%89%9B%E5%9C%BA%E8%8C%B6%E5%9C%BA_-_panoramio.jpg','/demo/tea-media/image-duyun-tea-farm-01.jpg','CC BY 3.0','https://creativecommons.org/licenses/by/3.0','kuaimei','image/jpeg','653948','b636f40b96f8326c24db563f7402623bb45882d8edbbcae3d30904911fc6d034','96','downloaded_and_hashed','开放许可的贵州都匀实拍，可按署名许可用作地点素材。','{"commonsTitle":"File:都匀牛场茶场 - panoramio.jpg","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/a/a6/%E9%83%BD%E5%8C%80%E7%89%9B%E5%9C%BA%E8%8C%B6%E5%9C%BA_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"Taken on 4 April 2011","width":3456,"height":2304,"downloadedAt":"2026-08-29T18:10:02.907Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('image-duyun-tea-farm-02','org-demo-guikesong','ent-demo-matcha','image','都匀牛场茶场 - panoramio (1).jpg','贵州茶园','open_media','贵州都匀实拍','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3A%E9%83%BD%E5%8C%80%E7%89%9B%E5%9C%BA%E8%8C%B6%E5%9C%BA_-_panoramio_(1).jpg','/demo/tea-media/image-duyun-tea-farm-02.jpg','CC BY 3.0','https://creativecommons.org/licenses/by/3.0','kuaimei','image/jpeg','763394','89f25c52da3a2115165d5f8234021e4e6791a8bd7b0e2dc5b1d9bf795bb107b7','96','downloaded_and_hashed','开放许可的贵州都匀实拍，可按署名许可用作地点素材。','{"commonsTitle":"File:都匀牛场茶场 - panoramio (1).jpg","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/6/63/%E9%83%BD%E5%8C%80%E7%89%9B%E5%9C%BA%E8%8C%B6%E5%9C%BA_-_panoramio_%281%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"Taken on 4 April 2011","width":3456,"height":2304,"downloadedAt":"2026-08-29T18:10:03.329Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('image-duyun-tea-farm-03','org-demo-guikesong','ent-demo-matcha','image','都匀牛场茶场 - panoramio (2).jpg','贵州茶园','open_media','贵州都匀实拍','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3A%E9%83%BD%E5%8C%80%E7%89%9B%E5%9C%BA%E8%8C%B6%E5%9C%BA_-_panoramio_(2).jpg','/demo/tea-media/image-duyun-tea-farm-03.jpg','CC BY 3.0','https://creativecommons.org/licenses/by/3.0','kuaimei','image/jpeg','868816','edeaad0bbb66d5479b92770eac35d2b45db26916ffb75160afa81bc9bb4a28fc','96','downloaded_and_hashed','开放许可的贵州都匀实拍，可按署名许可用作地点素材。','{"commonsTitle":"File:都匀牛场茶场 - panoramio (2).jpg","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/4/47/%E9%83%BD%E5%8C%80%E7%89%9B%E5%9C%BA%E8%8C%B6%E5%9C%BA_-_panoramio_%282%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"Taken on 4 April 2011","width":3456,"height":2304,"downloadedAt":"2026-08-29T18:10:03.716Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('image-wuyishan-plantation','org-demo-guikesong','ent-demo-matcha','image','China Wuyishan Tea Plantation.jpg','中国茶园','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3AChina_Wuyishan_Tea_Plantation.jpg','/demo/tea-media/image-wuyishan-plantation.jpg','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0','Lennartbj','image/jpeg','1531325','fed50d58fe2433dca9bf0cae4354d1c2fef6b247757d2a5f72d25e4ca4e77345','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:China Wuyishan Tea Plantation.jpg","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/f/f5/China_Wuyishan_Tea_Plantation.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2019-01-21 10:24:27","width":2976,"height":3968,"downloadedAt":"2026-08-29T18:10:04.109Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('image-dragon-well-plantation','org-demo-guikesong','ent-demo-matcha','image','Dragon Well Tea Plantation (25876276577).jpg','中国茶园','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ADragon_Well_Tea_Plantation_(25876276577).jpg','/demo/tea-media/image-dragon-well-plantation.jpg','CC BY 2.0','https://creativecommons.org/licenses/by/2.0','David Stanley from Nanaimo, Canada','image/jpeg','227017','3f41bdb03f6880b3bc68a3bacbf8fc335c68735e09bdf40d6e7d6e1ae83cbabc','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Dragon Well Tea Plantation (25876276577).jpg","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/6/6a/Dragon_Well_Tea_Plantation_%2825876276577%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2018-01-23 14:08","width":1024,"height":768,"downloadedAt":"2026-08-29T18:10:04.469Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('image-tea-fields-buddhist','org-demo-guikesong','ent-demo-matcha','image','Tea fields in front of Buddhist symbols.jpg','茶园景观','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ATea_fields_in_front_of_Buddhist_symbols.jpg','/demo/tea-media/image-tea-fields-buddhist.jpg','CC BY 2.0','https://creativecommons.org/licenses/by/2.0','Taco Witte','image/jpeg','864788','a924470e7dbcb8d88fa55960de55be25a3cfdc92a737be7d370a9b9f593f5557','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Tea fields in front of Buddhist symbols.jpg","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/a/a3/Tea_fields_in_front_of_Buddhist_symbols.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2010-02-11 06:15:03","width":2816,"height":2112,"downloadedAt":"2026-08-29T18:10:04.885Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('image-china-tea-fields','org-demo-guikesong','ent-demo-matcha','image','Fields of tea.jpg','中国茶园','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3AFields_of_tea.jpg','/demo/tea-media/image-china-tea-fields.jpg','CC BY 2.0','https://creativecommons.org/licenses/by/2.0','Robbie Sproule from Montreal, Canada','image/jpeg','294789','faece98b0de1eb6ebbca8f5b8ed3a7351347bfdf4a8b4fc9cb75055be93d251e','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Fields of tea.jpg","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/0/04/Fields_of_tea.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2004-02-08 05:25:59","width":1600,"height":1200,"downloadedAt":"2026-08-29T18:10:05.307Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('image-tea-grower-hangzhou','org-demo-guikesong','ent-demo-matcha','image','Tea-grower-hangzhou.jpg','采茶人物','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ATea-grower-hangzhou.jpg','/demo/tea-media/image-tea-grower-hangzhou.jpg','Public domain','https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia','JalalV','image/jpeg','686274','efd31ec68c9582b5bbf86443286fda3b093cbf53247f1dc64aab31ce0873f121','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Tea-grower-hangzhou.jpg","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/1/1e/Tea-grower-hangzhou.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2008-05","width":2304,"height":3072,"downloadedAt":"2026-08-29T18:10:05.683Z","attributionRequired":false}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('image-tea-processing-diagram','org-demo-guikesong','ent-demo-matcha','image','TeaprocessingZh-small.png','加工知识图','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ATeaprocessingZh-small.png','/demo/tea-media/image-tea-processing-diagram.png','CC BY-SA 3.0','http://creativecommons.org/licenses/by-sa/3.0/','Teaprocessing-small.png: sjschen
derivative work: sjschen','image/png','71929','0c62548ac62e2c5d53bf00896de91253f5d58ba71bafeea1b976b2f6d4f7ebeb','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:TeaprocessingZh-small.png","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/d/df/TeaprocessingZh-small.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2009-11-16 23:20","width":1280,"height":676,"downloadedAt":"2026-08-29T18:10:06.054Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,source_url,local_path,license_name,license_url,author,mime_type,bytes,sha256,quality_score,verification_status,truth_notice,metadata_json) VALUES ('image-bi-luochun','org-demo-guikesong','ent-demo-matcha','image','Bi Luochun.jpg','茶叶产品','open_media','茶行业通用参考','Wikimedia Commons','https://commons.wikimedia.org/wiki/File%3ABi_Luochun.jpg','/demo/tea-media/image-bi-luochun.jpg','CC BY-SA 3.0','https://creativecommons.org/licenses/by-sa/3.0','Template:Windbell','image/jpeg','209860','f5d8c57f70698d0fa237962f21a3f96838e258ea9eae4fb4a382a2e406380de4','90','downloaded_and_hashed','开放许可的茶行业通用参考，不代表贵州本地、当前企业或其生产能力。','{"commonsTitle":"File:Bi Luochun.jpg","originalUrl":"https://upload.wikimedia.org/wikipedia/commons/d/d6/Bi_Luochun.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original","capturedAt":"2010-08-02","width":450,"height":435,"downloadedAt":"2026-08-29T18:10:06.407Z","attributionRequired":true}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-enterprise-profile','org-demo-guikesong','ent-demo-matcha','enterprise','贵州茶产业演示企业','企业主体','mock','贵州','Qianhai Demo generator','92','schema_validated_mock','Mock：用于演示企业资料、团队、权限和增长任务，不对应真实企业。','{"fields":["企业名称","产业定位","目标市场","团队角色","权限边界"]}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-industry-profile','org-demo-guikesong','ent-demo-matcha','industry','贵州茶行业经营画像','产业画像','mock','贵州','Qianhai Demo generator','90','schema_validated_mock','Mock：覆盖种植、初制、精制、品牌和出口场景；规模、份额和经营指标不得当作真实统计。','{"chain":["茶园","初制","精制","品牌","渠道"]}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-product-green-tea','org-demo-guikesong','ent-demo-matcha','product','都匀毛尖出口装 Demo','绿茶产品','mock','贵州','Qianhai Demo generator','88','schema_validated_mock','Mock：模拟规格、包装与报价参数，产品名称仅用于行业演示。','{"grade":"特级/一级 Demo","package":"100g/250g/1kg Demo"}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-product-matcha-food','org-demo-guikesong','ent-demo-matcha','product','贵州食品级抹茶 M-01','抹茶产品','mock','贵州','Qianhai Demo generator','90','schema_validated_mock','Mock：模拟产品与交易参数，不代表任何企业真实产能或认证。','{"application":["烘焙","巧克力"],"moq":"Demo 800kg"}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-product-matcha-drink','org-demo-guikesong','ent-demo-matcha','product','贵州饮品级抹茶 M-02','抹茶产品','mock','贵州','Qianhai Demo generator','90','schema_validated_mock','Mock：模拟产品与交易参数，不代表任何企业真实产能或认证。','{"application":["奶茶","咖啡"],"moq":"Demo 1000kg"}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-product-tea-bag','org-demo-guikesong','ent-demo-matcha','product','贵州绿茶袋泡茶 Demo','消费茶产品','mock','贵州','Qianhai Demo generator','84','schema_validated_mock','Mock：模拟零售产品、包装和渠道定位。','{"package":"20袋/盒 Demo","market":"新加坡 Demo"}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-product-cold-brew','org-demo-guikesong','ent-demo-matcha','product','贵州冷泡茶原料 Demo','茶饮原料','mock','贵州','Qianhai Demo generator','84','schema_validated_mock','Mock：模拟配方应用和买家沟通场景。','{"application":["冷泡茶","即饮茶"],"sample":"100g Demo"}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-buyer-importer','org-demo-guikesong','ent-demo-matcha','buyer_persona','食品原料进口商','采购角色','mock','东南亚','Qianhai Demo generator','86','schema_validated_mock','Mock：模拟买家画像，用于资格判断和内容选题。','{"needs":["稳定供货","批次检测","合规资料"]}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-buyer-cafe-chain','org-demo-guikesong','ent-demo-matcha','buyer_persona','咖啡与新茶饮连锁','采购角色','mock','东南亚','Qianhai Demo generator','86','schema_validated_mock','Mock：模拟买家画像，用于菜单测试和样品流程。','{"needs":["颜色","口感","单杯成本"]}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-buyer-distributor','org-demo-guikesong','ent-demo-matcha','buyer_persona','区域茶叶经销商','渠道角色','mock','东南亚','Qianhai Demo generator','84','schema_validated_mock','Mock：模拟买家画像，不代表真实客户。','{"needs":["渠道利润","包装","非独家试销"]}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-content-origin','org-demo-guikesong','ent-demo-matcha','content_brief','贵州茶产地故事图文','内容任务','mock','贵州','Qianhai Demo generator','91','schema_validated_mock','Mock：引用开放图片时必须按许可署名；不得把行业素材说成企业自有茶园。','{"format":"carousel","channel":"LinkedIn"}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-content-harvest','org-demo-guikesong','ent-demo-matcha','content_brief','一芽一叶采摘流程短视频','内容任务','mock','行业通用','Qianhai Demo generator','91','schema_validated_mock','Mock：用开放行业视频解释流程，必须显示“行业参考画面”。','{"format":"short_video","channel":"Instagram"}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-content-processing','org-demo-guikesong','ent-demo-matcha','content_brief','绿茶加工节点知识卡','内容任务','mock','行业通用','Qianhai Demo generator','90','schema_validated_mock','Mock：依据开放加工流程图制作，不宣称具体企业采用相同工艺。','{"format":"knowledge_card","channel":"Website"}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-content-quality','org-demo-guikesong','ent-demo-matcha','content_brief','海外买家验厂五项清单','内容任务','mock','东南亚','Qianhai Demo generator','93','schema_validated_mock','Mock：质量、认证和产能字段均需企业人工确认。','{"format":"checklist","channel":"LinkedIn"}');
INSERT INTO tea_industry_catalog (id,organization_id,enterprise_id,item_type,title,category,classification,geography_scope,source_name,quality_score,verification_status,truth_notice,metadata_json) VALUES ('mock-campaign-sea','org-demo-guikesong','ent-demo-matcha','campaign','贵州茶东南亚市场验证','增长任务','mock','马来西亚/新加坡','Qianhai Demo generator','88','schema_validated_mock','Mock：预算、流量、询盘和成交指标全部为 Demo。','{"budget_cny":30000,"qualified_inquiries":6}');

PRAGMA optimize;
